[package]
name = "realpath"
version = "0.1.1"
authors = ["boxdot <d@zerovolt.org>"]
license = "MIT/Apache-2.0"
description = "returns the canonicalized absolute pathname"
repository = "https://github.com/boxdot/realpath-rs"

[dependencies]
